### ISSUE TITLE
Unassigned parent attributes in Regularizations

### ISSUE THREAD

**Issue by johnweis0480** [simpeg/simpeg#1341]
### Describe the issue:

I believe the structure of simpeg inheritance is causing issues. I have been trying to reproduce old codes from Simpeg 0.18.0 and do not believe the argument for 'gradient_type' is the Sparse regularization is working. It looks like this is due to inheritance and setters in the current simpeg, especially with the 'parent' attribute.

It seems that a lot of these classes that rely on complex and deep inheritance have had issues and could potentially be simplified. If this is not the case, it would be nice to put in some tests to make sure that these classes have the intended behavior.

### Reproducable code example:

```python
reg = regularization.VectorAmplitude(
    mesh,
    mapping=idenMap,
    active_cells=actv,
    reference_model_in_smooth=True,
    norms=[0.0, 2.0, 2.0, 2.0],
    gradient_type="total",
)
```

### Runtime information:

Not applicable

**Comment by jcapriot** [comment]
The structure of the regularizations can get a bit confusing. It would appear that the Sparse Smoothness operators depend on having a parent assigned for the `total` gradient to work, but it would appear that the `parent` is never set anywhere.

Looking at the codecov reports as well, it doesn't look like any of the tests touch the Smoothness operator's `parent` setter attribute. This also explains why the lines for the `total` gradient in Sparse Smoothness are never assigned (because `parent` is always evaluating as `None`). I'm going to update the title of this to reflect the bug, and sick @domfournier on this bug.

**Comment by domfournier** [comment]
Yea I guess we never formalized the concept of `parent`. I would propose to add a objfcts.setter on the `ComboObjectiveFunction` so that any sub-function can know about its parental combo. I ll add unitests of course.
