### ISSUE TITLE
warning with default solver 

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#1563]
I appreciate the idea of wanting to alert users that a default solver is being used, but it is odd that if I am writing a tutorial or example and want to explicitly set the default solver, that I get a warning (e.g. in the following figure). A warning usually implies that I should change my code, but here, it is just information. For the purposes of a tutorial, I then opt not to use the handy functionality of getting a default solver because having a warning message pop up is distracting (and I don't want to be promoting that users should suppress all warnings). 

![image](https://github.com/user-attachments/assets/6f558e37-60c1-42a4-ada8-6222fc8a73ca)

So, then the question is what to do. I would suggest that we remove the warning and instead include a statement in the inversion log about what solver is being used (we could also add this as a statement that is printed out when running a "verbose" simulation, but I know that we don't have that option implemented uniformly across all simulations at the moment). Totally open to other suggestions too, but I think that when a user explicitly calls `get_default_solver` that we shouldn't throw a warning at them.

**Comment by jcapriot** [comment]
I think having a message for simulations is pretty important because the choice of solver is very impactful to the runtime of the PDE simulations, so if the user never sets the solver, they should be more aware of which solver is getting used. 

I don’t think having the users suppress all warnings is a good idea either, but fortunately they can suppress that specific warning if they choose, and if they do not, it should only ever be issued once. Unfortunately if this was just a print statement, there would be no way to disable it unless we had different verbosity levels, which is something we don’t support. Until we do, I think it should stay a warning.

We could change where the warning is issued though, by spitting it into two functions:
* the public `get_default_solver` which would change to not issue the warning but have the same functionality, as you could expect someone to use that to knowingly choose a default solver.
* a private method `_get_default_solver` which issues a warning (and then returns the result of `get_default_solver`). This would be the function used internal to SimPEG, when it asks for the solver, as most will be unaware of this even being a thing that happens. For example it would be called by PDE simulations if the solver class was never set.

On top of this, we could also handle this case:
* If the user calls `set_default_solver` probably don’t need to issue the warning at any point.
