### ISSUE TITLE
adding Utils.Zero()

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#164]
On linux, the operation 

```
s = np.random.rand(1)
s += Zero()
```

fails: see https://travis-ci.org/simpeg/simpeg/jobs/90000058 (on the branch ZeroIdentityTest)

**Comment by lheagy** [comment]
also, it doesn't play nicely with sparse matricies, vectors (see test_Zero on the branch ZeroIdentityTest)

```
z = Zero()
sm = sp.random(10,10,density=0.2)
sm*z 
```

**Comment by lheagy** [comment]
<img width="528" alt="zero" src="https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png">

**Comment by bsmithyman** [comment]
The code looks good, but it might be that numpy is triggering a special
case of some kind and triggering __rmul__ once for each term in the random
vector, rather than rmul for the array as a whole. Maybe there's a way to
identify as array compatible so it doesn't get broadcasted. Could also be
__float__ that's the issue.

On Sun, Nov 8, 2015, 7:37 PM Lindsey <notifications@github.com> wrote:

<
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
img
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
src
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
="
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
https
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
://
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
ci5.googleusercontent.com
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
/proxy/4uYJQbJgMd0jq4p6l7bSTzU4uzCwn_5OQCFTU2dcjaEbPsXwAcyQJogheVYrnCo_zALM-eSZT4rV54VpkQUGfXo
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>

-
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
TAV7NmM1V9SP3rjoYT94PS5gGWLF
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
_
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
kvqS44nYf1R0iTn5cjlvl1iLwy3WmgwTHSKpn
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
--CA4L7BA
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
=s0-d-e1-ft#https://
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
cloud.githubusercontent.com
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
/assets/6361812/11023775/
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>
">
<https://cloud.githubusercontent.com/assets/6361812/11023775/e82ba4e4-8636-11e5-9d24-c5abc145ecc5.png>

—
Reply to this email directly or view it on
<https://github.com/simpeg/simpeg/issues/164#issuecomment-154891621>GitHub
<https://github.com/simpeg/simpeg/issues/164#issuecomment-154891621>.<img
src="
https://ci5.googleusercontent.com/proxy/GcJkEByJnR1V9B2Mcs-1ODWumlbbaUD20kIXvrt9q5YKP3aFHwE3DFPKmDWr6TQ4CmNCgzuVT9hmgTg8sT1NcNJJFHm532Z47gJIREGFwoZk1rtP4alUmdgDf6WtBOnDJe1BRnvD3t_fWGo49oiyAY_UU4cETA=s0-d-e1-ft#https://github.com/notifications/beacon/AEEl_RSFAWZxpAdwPhvzVZVNiexYL6LYks5pD-JCgaJpZM4GeQli.gif
">

**Comment by bsmithyman** [comment]
First error is b/c `scipy.sparse` matrices [don't support `__iadd__`](https://github.com/scipy/scipy/blob/master/scipy/sparse/base.py#L455-L456). Not sure if there's a way around this, other than to do `v = v + Zero()`.

A lot of the other errors come because the `scipy.sparse` matrix types never call your `__radd__`, etc. I think it might come down to how `numpy`'s `isscalar` works. Not sure if this is useful, but:

If you want to figure out if a given method is being called by a method on a sparse vector, this is possible, but it's super hackish and won't work outside CPython:
```python
    @property
    def _compatible(self):
        import inspect
        frame = inspect.currentframe()
        caller = frame.f_back.f_back.f_locals.get('self', None)
        if caller is not None and isinstance(caller, sp.base):
            return False
        return True
    def __abs__(self):return 0 if self._compatible else None
```

**Comment by lheagy** [comment]
It would be handy if we could figure out if there is an easy way to tell numpy and scipy to use the zero class methods (ie 

```
a = np.random.rand
z = Zero()

a.__add__(z)
```

would trigger

```
z.__add__(a)
```

**Comment by lheagy** [comment]
Should we initialize these with a size for now until we can figure out a work around? (make travis happy?)

**Comment by lheagy** [comment]
It is actually handy in a number of cases to not initialize with a size (ie. for FDEM, switching between formulations means that your source loc changes from faces to edges, but might be zero in either case). I can get the em/ZeroIdentity branch passing on my machine (both my mac and linux), but when running on travis, I get a TypeError. Any thoughts on a work-around?
```
TypeError: ufunc 'add' output (typecode 'O') could not be coerced to provided output parameter (typecode 'D') according to the casting rule ''same_kind''
```

**Comment by bsmithyman** [comment]
I'm not super familiar with numpy ufuncs, but I'll try to take a look today. I think part of the problem in general is the `__radd__` behavior of `np.compressed, or lack thereof.

**Comment by lheagy** [comment]
Thanks Brendan, I have played around a bit this morning, and the issue seems to be with numpy's __iadd__ (+=). If I replace all a+= b with a = a+b, it seems to be more stable.

**Comment by rowanc1** [comment]
Are the errors:

```python
TypeError: Cannot cast array data from dtype('O') to dtype('complex128')
according to the rule 'safe' ```
working on your computer?

On Tue, 24 Nov 2015 at 11:33 Lindsey <notifications@github.com> wrote:

> Thanks Brendan, I have played around a bit this morning, and the issue
> seems to be with numpy's *iadd* (+=). If I replace all a+= b with a =
> a+b, it seems to be more stable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simpeg/simpeg/issues/164#issuecomment-159381858>.
>

**Comment by rowanc1** [comment]
Are the errors:

```python
TypeError: Cannot cast array data from dtype('O') to dtype('complex128') according to the rule "safe"
```

working on your computer?

**Comment by lheagy** [comment]
I pushed some changes this morning, and can get the em/ZeroIdentity branch passing on my machine. But I am now running into errors when solving and not using Mumps (Mumps seems to be able to deal with it). If you run the tests in fdem/forward, do you run in to issues?

**Comment by lheagy** [comment]
when adding Zero(), it changes the dtype of a numpy array which is causing issues with the solver object

```
In [1]: from SimPEG.Utils import Zero

In [2]: import numpy as np

In [3]: a = np.random.rand(5)

In [4]: a.dtype
Out[4]: dtype('float64')

In [5]: z = Zero()

In [6]: (a+z).dtype
Out[6]: dtype('O')
```
