### ISSUE TITLE
Assigning of Wd in Data misfit.

### ISSUE THREAD

**Issue by grosenkj** [simpeg/simpeg#169]
If not given, a default value of Wd is estimated in DataMisfit class irrespective of whether it is given in survey object or not. Shouldn't DataMisfit use Wd from survey if it is given?

**Comment by rowanc1** [comment]
That seems like ideal behaviour, and what I thought was going on. I will
look into this, it could be assigned in the inversion class?

**Comment by rowanc1** [comment]
The default behaviour of the data misfit is to create a `Wd` using the `std` of the survey plus a noise floor. This can be changed by setting `Wd` directly in the `DataMisfit`. I don't think that the survey should have a `Wd`, it does, however, have the standard deviations and the observed data. It is possible to override the defaults by just setting `Wd` directly. I have copied the relevant code below.

Is this the expected behaviour @grosenkj?

```python
@property
def Wd(self):
    """getWd(survey)

        The data weighting matrix.

        The default is based on the norm of the data plus a noise floor.

        :rtype: scipy.sparse.csr_matrix
        :return: Wd

    """

    if getattr(self, '_Wd', None) is None:
        print 'SimPEG.l2_DataMisfit is creating default weightings for Wd.'
        survey = self.survey
        eps = np.linalg.norm(Utils.mkvc(survey.dobs),2)*1e-5
        self._Wd = Utils.sdiag(1/(abs(survey.dobs)*survey.std+eps))
    return self._Wd
```

**Comment by grosenkj** [comment]
@rowanc1, thanks for the reply. 

The default assigning of `Wd` in `DataMisfit` makes sense but I was confused by the fact it was not considering the already exciting one in `Survey` (which I now know should be there). I have been overriding with `DataMisfit.Wd = Survey.Wd`, but I thought that was redundant and should be included in the default behaviour of `DataMisfit.Wd`. I fully agree that having `Wd` in `Survey` should be there, but I have no idea how I came to assigning it there.

But you answer clarified this confusion of mine. 
Thanks.
