### ISSUE TITLE
Problem with aveE2CCV when used on a cylindrical mesh

### ISSUE THREAD

**Issue by micmitch** [simpeg/simpeg#367]
Use of the aveE2CCV function reduces values by a factor of 0.5 when used on a cylindrical mesh. 

Below is a simple example which shows this behaviour.

`# import unittest
from SimPEG import EM, Mesh, Utils, np, Maps, sp
# import sys
from scipy.constants import mu_0
%pylab inline
import matplotlib.pyplot as plt

# Create cylindrical mesh
csx, ncx, npadx = 5, 50, 25
csz, ncz, npadz = 5, 50, 25
hx = Utils.meshTensor([(csx, ncx), (csx, npadx, 1.3)])
hz = Utils.meshTensor([(csz, npadz, -1.3), (csz, ncz), (csz, npadz, 1.3)])
mesh = Mesh.CylMesh([hx, 1, hz], [0., 0., -hz.sum()/2])

# Dummy H function which lives on edges
h_e = np.ones(mesh.nEy)

# average to CC
h_cc = mesh.aveE2CCV*h_e

# Measurement locations for comparison
rlim = [20., 500.]
r = mesh.vectorCCx[np.argmin(np.abs(mesh.vectorCCx-rlim[0])):np.argmin(np.abs(mesh.vectorCCx-rlim[1]))]
z = 100.
XYZ = Utils.ndgrid(r, np.r_[0.], np.r_[z])

# Create data projection matrices
Pcc = mesh.getInterpolationMat(XYZ, 'CC')
Pey = mesh.getInterpolationMat(XYZ, 'Ey')

h_cc_test = Pcc*h_cc
h_e_test = Pey*h_e

# Plot
plt.subplot(211)
plt.plot(r,h_cc_test.real,'o',r,h_e_test.real,linewidth=2)
plt.grid(which='both')
plt.title('H_y Real')
plt.xlabel('r (m)')

plt.subplot(212)
plt.plot(r,h_cc_test.imag,'o',r,h_e_test.imag,linewidth=2)
plt.grid(which='both')
plt.title('H_y Imag')
plt.legend(['Num','Ana'],bbox_to_anchor=(1.5,0.5))
plt.xlabel('r (m)')

plt.tight_layout()
`

![image](https://cloud.githubusercontent.com/assets/13682778/17122014/c0c97af2-528c-11e6-8d99-8f7c06a3c2a2.png)

**Comment by rowanc1** [comment]
See number #56 as well potentially.

I think there is some weak testing on averaging, but that may not have made it over to the cyl mesh stuff.

This is possibly the difference between the `aveE2CCV` and the `aveE2CC` which is the non-vector form.

Is there any chance that you could rework your code into a nosetest? Similar to:
https://github.com/simpeg/simpeg/blob/master/tests/mesh/test_tensorMesh.py#L8

Maybe `test_averaging.py`? with a branch name something like: `bug/cylmesh-aveE2CCV`

In the tensor mesh we just call each averaging component individually. I think that we copied that code over to the cyl mesh and dropped the `x` component because there is actually only one edge. This is probably sloppy, and either way should have a unit test.

The tensor mesh stuff, note each averaging component:
![image](https://cloud.githubusercontent.com/assets/913249/17123607/f170112e-52a1-11e6-99bd-48f4393ac24a.png)

Whereas in the cyl code:
![image](https://cloud.githubusercontent.com/assets/913249/17123691/9019defe-52a2-11e6-9c13-bb5b5c91477a.png)

So I think the fix is the 2x on:
https://github.com/simpeg/simpeg/blob/master/SimPEG/Mesh/CylMesh.py#L297

**Comment by rowanc1** [comment]
@lheagy should we even have a vector average really in this code? Only for consistency? Is the `aveE2CC` correct here?

**Comment by lheagy** [comment]
It really is only for consistency, there is only one edge, so `aveE2CC` and `aveE2CCV` should be identical. I do think it is worth having `aveE2CCV` in the namespace for consistency, but perhaps it just calls `aveE2CC` for code clarity

**Comment by rowanc1** [comment]
So my 2x is probably in the wrong place. The 0.5 may need to be removed.
