### ISSUE TITLE
Bug: Linear Problem

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#509]
I re-ran the linear problem (http://docs.simpeg.xyz/content/examples/Inversion_Linear.html) on the dev branch and now get 
![image](https://cloud.githubusercontent.com/assets/6361812/20417265/1224f342-acf9-11e6-9edd-31bfddb937dd.png)

while on master we recover something much more reasonable

![image](https://cloud.githubusercontent.com/assets/6361812/20417297/38e591e4-acf9-11e6-856a-007e669b62ec.png)

a random seed is set, so it not just a one-off. This needs to be resolved prior to putting any pr from dev to master!

**Comment by rowanc1** [comment]
![image](https://cloud.githubusercontent.com/assets/913249/22035471/f8564476-dca4-11e6-926f-47aa2f2a9e56.png)

I added more data and removed the beta schedule.

**Comment by rowanc1** [comment]
It is a bit disconcerting that the thing changed, this is probably due to a random call though somewhere that got added, changing the random seed. The fact that it now doesn't work that well doesn't actually surprise me that much. I tuned the inversion pretty heavily to start with. Now with more frequencies, it is much more stable.
