### ISSUE TITLE
Import UBC mesh error 

### ISSUE THREAD

**Issue by fourndo** [simpeg/simpeg#548]
Problem when attempting to load this UBC mesh, number of cells in X truncated. Not sure why...

78 50 51
-200000.000000 -200000.000000 3000.000000
55000 45000 40000 35000 25000 10 * 20000 3 * 10000 43 * 10000 2 * 10000 10 * 20000 25000 35000 40000 45000 55000 
70000 50000 40000 25000 15000 40 * 20000 15000 25000 40000 50000 70000 
12 * 250 24 * 2500 8 * 5000 7500 10000 12500 15000 15000 20000 20000

**Comment by grosenkj** [comment]
Is the definition of the sizes in the `x` (`h_x`) direction split into 2 lines? Are you missing 3 cells from your model?

The `readUBC` function assumes the line structure to be
1. nrC_x, nrC_y, nrC_z
2. refLoc_x, refLoc_y, refLoc_ z
3. h_x
4. h_y
5. h_z

This would be my first guess.

**Comment by fourndo** [comment]
nice try for 1:15 am, but nay :) It's got to be deeper than this. The output mesh ends up being in hx:
array([  55000.,   45000.,   40000.,   35000.,   25000.,   20000.,
         20000.,   20000.,   20000.,   20000.,   20000.,   20000.,
         20000.,   20000.,   20000.,   10000.,   10000.,   10000.,
        410000.,   10000.,   10000.,   10000.,   10000.,   20000.,
         20000.,   20000.,   20000.,   20000.,   20000.,   20000.,
         20000.,   20000.,   20000.,   25000.,   35000.,   40000.,
         45000.,   55000.])

so there is a truncation somewhere. It works if I get rid of the redundant  3 * 10000 43 * 10000 2 * 10000 and change it to 48 * 10000. But I don't get the final result (41000 ?!)

**Comment by grosenkj** [comment]
It was worth it. 

In this case, try removing the spaces around the `*`. In the code a whitespace identifies different portions of the tensor (thickness or number of cells times thickness), so having the space around likely affects that. I am not sure why it works for the other directions, but ...

**Comment by fourndo** [comment]
the space was just to past here, otherwise it shows as italic...

**Comment by rowanc1** [comment]
@fourndo you can put your plain text stuff in three back-ticks to preserve formatting...

<code>```</code>

**Comment by grosenkj** [comment]
@fourndo Sorry for the delay, but I found the bug. It has to do with how `readUBC` reads the multiplied cells (`3*10000 43*10000`). The function used `string.replace` to replace the `-*-` in the input lines  and then read the lines in. But in your `x` direction since you have two strings that match the `3*10000` both got replaced with `10000 10000 10000` producing the errorous `10000 10000 10000 410000 10000 10000` segment in your mesh. 

Since the `Mesh` package has been moved to the `discritize` module I updated the `readUBC` util there to address this bug in this pull request [Updating MeshIO, to address string replacement bug. #38](https://github.com/simpeg/discretize/pull/38).

**Comment by rowanc1** [comment]
Can we include a copy of the offending mesh so that we keep this bug fixed into the future? Thanks @grosenkj for fixing the bug in `discretize`!

I would like to throw another test on the meshIO before putting that PR in. I can help out if you provide the mesh file (slack or git commit it on the PR). Currently we are only testing that we can read a mesh that we wrote.

**Comment by fourndo** [comment]
You're the man @grosenkj 
Here's a file.
[BadMesh.txt](https://github.com/simpeg/simpeg/files/825095/BadMesh.txt)

**Comment by rowanc1** [comment]
Thanks, I have included it in the PR!

**Comment by rowanc1** [comment]
This is now on the dev branch of discretize. I will close this when we do a redeploy.

**Comment by lheagy** [comment]
This will be deployed with simpeg/discretize#46

**Comment by lheagy** [comment]
This was closed with the merge of simpeg/discretize#46
