### ISSUE TITLE
Combo Objective function

### ISSUE THREAD

**Issue by fourndo** [simpeg/simpeg#559]
The new regularization structure proposed by @lheagy is a two-level nesting of lists. The first level is the standard Combo Regularization object containing a list of base regularizations:

`reg1 = [reg.Small, reg.Derivx, reg.Derivy, reg.Derivz]`

Then there is the option of a higher level if combining regularizations (i.e. for different portions of the model using `Maps.Wires`)

`reg = reg1 + reg2 `

In which case we get a list of ComboObj

`reg = [reg1, reg2]`

So the issue is if I pass **reg** OR **reg1** to a function/directive, the function needs to adapt in order to change the variables on the first or second level of the list. Here is my current work around:

```python
def initialize(self):

        # Check if it is a ComboObjective
        if not isinstance(self.reg, Regularization.BaseComboRegularization):

            # It is a Combo objective, so will have to loop
            self.ComboObjFun = True

        # Don't worry about this line
        if self.mode == 1:

           # Here is the hack, needs an inner loop to touch the elements of each combo
            if self.ComboObjFun:

                self.norms = []
                for reg in self.reg.objfcts:
                    self.norms.append(reg.norms)
                    reg.norms = [2., 2., 2., 2.]

            else:
                # Just act on the first level
                self.norms = self.reg.norms
                self.reg.norms = [2., 2., 2., 2.]
```

**Comment by rowanc1** [comment]
In this case do you just want to update all of the norms?

Maybe we could have a property in there that returns the regularizations as if it were `flatten`ed?

In which case you could have a single piece of code that says:

```python
for reg in self.reg.flatten():
    reg.norm = 2.
```

This would also work if perhaps your code was used with something that was more 2D in nature (e.g. symmetric cyl mesh?) and only has three sub-regularizations.

I think this would only fix this issue, and we will run into this again in quite a few different ways. Not quite sure of the way out yet!

cc @lheagy

**Comment by lheagy** [comment]
I like the idea behind `flatten`, but it is a little subtle. The behaviour @rowanc1 is describing would (in the current implementation) turn `reg` into a comboRegularization... 

In @fourndo's example case, `reg1` and `reg2` each potentially have their own `mref` and potentially different `cell_weights`. A comboRegularization would try to share these. My first idea around this would be to create an `expose('norms')` which (first checks that both `reg1` and `reg2` have a property called `norms`) and then adds that property to the top level `reg` so that when you do 
```
reg = reg1 + reg2
reg.expose('norms')
reg.norms = [2, 2, 2, 2]
```
reg would propagate that down to `reg1`, `reg2`.

**Comment by rowanc1** [comment]
I guess I wasn't quite clear. I meant that it "acted like", as in an iterator that would go through each of the regularizations, but would not actually transform the structure.

**Comment by lheagy** [comment]
My fear here is that there are really only a handful of things you might want to expose. `flattening` and giving hooks to all of them seems dangerous. For example, if using `wires` to properly map parameters to reg1 and a different set of parameters to reg2, we should not expose `mapping` at the top level. And if it appears in the namespace, that is a potential point of confusion. 
```
reg.expose(['mref', 'norms'])
```
or something along those lines is explicit about what you are giving hooks into.

**Comment by lheagy** [comment]
I have started a first pass of this on the branch feat/combo_directives (see: https://github.com/simpeg/simpeg/blob/feat/combo_directives/SimPEG/ObjectiveFunction.py#L356
and tests at: https://github.com/simpeg/simpeg/blob/feat/combo_directives/tests/base/test_Objectivefct.py#L321
)

![image](https://cloud.githubusercontent.com/assets/6361812/24832472/19474490-1c66-11e7-9220-3100b71dbd71.png)

I would appreciate thoughts and feedback prior to starting a pr! cc @rowanc1 :)

**Comment by lheagy** [comment]
The relevant diff is here: https://github.com/simpeg/simpeg/compare/feat/directives_validation...feat/combo_directives?expand=1

**Comment by lheagy** [comment]
@fourndo: do you think the current solution of casting all regularizations to combo for the directives is sufficient to close this?

**Comment by domfournier** [comment]
I think this is nice to be able to pass down changes to all components of a Combo.
I am guessing your question is related to #898 ?

We might just have to add another type of weights (regularization_weights vs function_weights?) since we are effectively trying to add another layer of nobs.

`cell_weights` is a bit of a misnomer for the gradient terms anyway ...
