### ISSUE TITLE
Failed Properties when importing DC

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#630]
Here is an error I get on my machine and Travis, using (I hope) all the latest versions of SimPEG, discretize and Properties. I also did a `make clean` prior to posting the issue.
Check the screenshot for more details:

Any ideas @rowanc1, @lheagy ,@fwkoch?

![monosnap 2017-07-20 14-44-39](https://user-images.githubusercontent.com/13682747/28440355-cdc0ad9a-6d5a-11e7-9423-d502915dab58.png)

**Comment by fwkoch** [comment]
Hi @thast - thanks for pointing this out - this is a problem with `properties`. Between v0.3.3 and v0.3.4, I attempted to clean up some code that looked like `if len(val) > 0:` to just `if val:`. This works for `list`s, but not `np.ndarray`s since they have a different way of determining truth.

I'll revert the changes in properties, but in the mean time, you can go back to `properties==0.3.3`, should be ok.

**Comment by fwkoch** [comment]
Ok, `properties v0.3.5` is now deployed and should contain a fix for this. Please re-open and let me know if you continue to have problems.

https://github.com/aranzgeo/properties/releases/tag/v0.3.5 - https://pypi.org/project/properties/

**Comment by thast** [comment]
Thanks @fwkoch, 0.3.5 fixed it!
