### ISSUE TITLE
 Optimization is sensitive to a scalar multiplication

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#636]
Multiplying the objective function by a scalar seems to change the step-size of the line search, and thus the outcome (or at least that is my best so far).

I tried it by adding a 'Chi' factor in front of the data misfit term in `invProblem`
The idea being that, optimizing `A(m) + beta* B(m)` is expected to be the same as optimizing `(1/beta)* A + B`

![simpeg git 2017-09-06 18-10-55](https://user-images.githubusercontent.com/13682747/30141225-ce865b4a-932e-11e7-9bf7-471b03ad816b.png)

Using the linear inverse example, I get this:
![figure 1 2017-09-06 18-11-54](https://user-images.githubusercontent.com/13682747/30141246-f0dbbc76-932e-11e7-89cc-0d0d03535ff3.png)

And one the inversion took almost twice as many iterations to reach the data misfit than the other one.

Idea: We should try with the comboObjecive function, see if `objectiveFunction` or `10*objectiveFunction` give similar results.

Code enclosed:

[LinearInversion_Opt_Chi_Beta.zip](https://github.com/simpeg/simpeg/files/1283180/LinearInversion_Opt_Chi_Beta.zip)

**Comment by thast** [comment]
Some additional details: This example shows a slight difference. However this has become an issue for me for the petrophysically constrained inversion, as I now have 2 competing misfit functions (this is how I detected this behavior at first). With these 2 competing misfit, the difference between the two outcomes `A(m) + beta* B(m)` and `(1/beta)* A + B` can be massive.

**Comment by rowanc1** [comment]
It has been a while since I have looked at this code. My guess is that there is an assumption on `phi_d` and `phi_m` being offset by a single scalar: `beta`.

So that means there might be somewhere else in the code that looks at `self.phi_d/m` or `self.phi_d/m_last` and assumes that they are offset by `beta`.

Does the problem persist if you put `chi` on the `self.phi_d` (not `_last`) parameter specifically? Or just set `phi_d` before it is saved to include `chi` (same thing)?

This isn't really ideal, but might narrow the problem at least.

**Comment by thast** [comment]
I am closing this as there hasn't been discussion in a long time. Please feel free to re-open if you have further comments to add.
