### ISSUE TITLE
Modelling and inverting marine CSEM response

### ISSUE THREAD

**Issue by shahir87** [simpeg/simpeg#717]
Hi,
Is it possible to model and invert marine CSEM response using SimPEG? If yes, I will appreciate if an example is made on this. 
Best regards,
Shahir

**Comment by prisae** [comment]
Hi @shahir87. As far as I know no, not at the moment (contributions welcome). For CSEM, I'd recommend:
- 1D: [Dipole1D](http://marineemlab.ucsd.edu/Projects/Occam/1DCSEM), [empymod](https://empymod.github.io)
- 2D: [Mare2DEM](http://mare2dem.ucsd.edu)
- 3D: [PetGEM](http://petgem.bsc.es) (only modelling)

**Comment by shahir87** [comment]
Thanks @prisae for your recommendation. I will check them.

**Comment by sgkang** [comment]
Hi @shahir87, @prisae's comment is correct. In theory, SimPEG-EM can be used to compute marine CSEM, but we have not used so far. So, you may need to explore that if you want to use SimPEG-EM for marine CSEM application. But, we can definitely help, and point you to right direction, so let us know if you have a specific application in mind. 

It's a bit of tangent, but we hooked up @prisae's `empymod` package as an app. So that might be a good starting point if you are new to marine CSEM.

https://mybinder.org/v2/gh/geoscixyz/em-apps/master?filepath=index.ipynb
