### ISSUE TITLE
What is the definition of misfit

### ISSUE THREAD

**Issue by dougoldenburg** [simpeg/simpeg#763]
I think we need two distinct words: one describes the normed value; the other describes the final item that is put into phi_d in the inversion and includes the normed value multiplied by a scalar. 

![image](https://user-images.githubusercontent.com/6361812/53839437-548b7200-3f4c-11e9-9615-a7c6c3e37dab.png)

![image](https://user-images.githubusercontent.com/6361812/53839452-5e14da00-3f4c-11e9-8530-44d88cfeadfd.png)

**Comment by thast** [comment]
Just to summarize my opinion here:
1) There are many options for normalizing (`1`, or `1/2` or `1/nd` (`nd`: number of data)). So whatever choice we make, we will have to be explicit about it and about the target misfit (`nd`, `nd/2` or `1`.).
2) I like the `1/2`, not (only) for the optimization or because it is already set up, but also (and that is a very biased reason I agree), is that it also comes naturally when thinking of the L2 norm as the representation of a Gaussian uncertainties on the data, and the `1/2` is part of the [definition of a Gaussian](https://en.wikipedia.org/wiki/Multivariate_normal_distribution):
![image](https://user-images.githubusercontent.com/13682747/53845659-c967a780-3f5e-11e9-920e-5dad586729b7.png)
3) If not `1/2`, my second choice would be `1/nd` for the data misfit , as then your target is always 1 no matter the number of data.

**Comment by lheagy** [comment]
This got us (@dougoldenburg, @sgkang and I tripped up again)... I would be quite in favour of removing the factor of 1/2 and pointing to the fact we are building on Parker, Oldenburg, ...

**Comment by santisoler** [comment]
Adding my two cents in the discussion after what @thibaut-kobold mentioned in #1332. I'm completely on board to stick with a convention and be super explicit about the definition and the implementation of objective functions.

On personal preference, I don't quite like the 1/2 for usability, but I get the mathematical aesthetics of it. For ultimate usability purposes, I think normalizing by the number of data points is the best choice: the target for the `phi_d` will be 1 for a `chi` factor of 1, so users don't need to keep the number of points in their buffer memory to interpret the values of `phi_d`.

I don't think we should normalize it by `n_data` right now, and I think removing the 1/2 as @lheagy did in #1326 it's one good move forward.
