### ISSUE TITLE
create mesh in separate file and read in script

### ISSUE THREAD

**Issue by ROSHIV** [simpeg/simpeg#779]
Hello, 
1. I need to create  mesh and put the center of mesh as center of data coordinate. but I want to create in separate file and read the mesh file in the script and do not know how?
this is what I put in script but need to create in separate file and read in script. 2. I have a question about last line I subtracted the origin of data but do not know if it is correct or not, is it needed to subtract for plotting?

# Create a mesh
    dx = 250. 
    dy = 250. 
    dz = 200.

    hxind = [(dx, 5, -1.3), (dx, 70), (dx, 5, 1.3)] 
    hyind = [(dy, 5, -1.3), (dy, 70), (dy, 5, 1.3)]
    hzind = [(dz, 5, -1.3), (dz, 25)]

    mesh = Mesh.TensorMesh([hxind, hyind, hzind], 'CCC')

    # Get index of the center
    midx = int(mesh.nCx/2)
    midy = int(mesh.nCy/2)

survey.srcField.rxList[0].locs =  survey.srcField.rxList[0].locs - [741250, 7301780,-mesh.vectorNz[-1]]

**Comment by fourndo** [comment]
Hi @ROSHIV ,

Few options for:

1- You probably want to shift the origin of the mesh instead of shifting your data.
`mesh.x0 = mesh.x0 + np.r_[dx, dy, dz]`
Since you have create the mesh `CCC`, you probably just need to shift it by the coordinates of the center of your survey.

2- You can [export the mesh in UBC format](http://discretize.simpeg.xyz/en/master/api/generated/discretize.MeshIO.TensorMeshIO.html#discretize.MeshIO.TensorMeshIO.writeUBC) and play around with the [coordinates of the origin](https://giftoolscookbook.readthedocs.io/en/latest/content/fileFormats/mesh3Dfile.html#d-mesh-file)

3- Alternatively, have a look at the [mesh_builder_xyz](http://discretize.simpeg.xyz/en/master/api/generated/discretize.utils.mesh_builder_xyz.html?highlight=mesh_builder#discretize.utils.mesh_builder_xyz) utility from `discretize`. It will center it by default for you.

Hope this helps.

**Comment by ROSHIV** [comment]
Thanks for your reply, but I do not shift origin of mesh, I want to shift data, put the coordinate of the center to be as the origin of the mesh. and create mesh with the center origin.

**Comment by jcapriot** [comment]
As dom wrote long ago, there are several formats for IO operations of discretize meshes, which are detailed more clearly in the documentation at https://discretize.simpeg.xyz
