### ISSUE TITLE
Montreal SimPEG meeting and Hackathon

### ISSUE THREAD

**Issue by thast** [simpeg/simpeg#793]
Many of the core SimPEG developers will be in Montreal for the IUGG meeting.
We plan to spend a day together to advance the development of SimPEG to a next stage.

This issue is to gather people ideas about the hottest topics to address in SimPEG and discuss the next orientations of the package that will be tackle during this meeting.

Topics and development ideas:

- The new SimPEG `Simulation` class by @lheagy (further discussions in PR #786) . This is a major (and welcome) change to the API. The Montreal meeting could be ideal for people to try it out and make sure that all methods will be correctly implemented within this new framework

- Push further the examples, tutorial and documentation. @dccowan already started this in PR #785 and in https://github.com/simpeg/discretize/pull/172

**Comment by banesullivan** [comment]
I won't be in attendance but I could schedule aside some time to be available remotely! Specifically, the topic of developing more examples and tutorials sounds exciting to me - let me know if I can help with any 3D viz ideas in these examples to help communicate how awesome SimPEG is!

**Comment by craigmillernz** [comment]
My schedule on the 17th is already very full sorry, I'm chairing a session and giving a talk, but I hope to catch up with y'all during the week at some stage.

**Comment by prisae** [comment]
I won't be around but I'll follow closely and will be here for any help I could give. My main interest is the possibility to use other 'kernels' (forward modellers) within the whole SimPEG-framework. According to @lheagy , that is something which will be made much easier with the Simulation-refactor.

**Comment by fourndo** [comment]
Re-factor PF

**Comment by lheagy** [comment]
From today's [SimPEG meeting](https://docs.google.com/document/d/1kQ1ZF1IgO3O4YcrTYHSL6gSfCW9drwgOHEzF2R_Hh6M/edit#heading=h.ble67qzidgte), the main items that came up to discuss are:
- The structure of the [data class](https://github.com/simpeg/simpeg/issues/202)
- Examples of parallelization 
    - one simulation, many models
    - domain decomposition 
- [receiver classes]()
- OcTree mesh wishlist (cc @sgkang, @fourndo) 
- Drivers / wrappers / express
- Viz & plotting: separating the ability to get plot-able aspects of an object from the rendering of a plot so that we can more easily plug in different plotting backends 

I will link relevant issues, and if there are others you would like to discuss, please add them here.

**Comment by thast** [comment]
Proposed high-level theme of the day: (towards) `SimPEG 1.0.0`

**Comment by sgkang** [comment]
## Thoughts on expanding SimPEG to handle large-scale EM problems

Three main applications that could make some impact to our community might be: MT, AEM, and CSEM. Having that in mind, I think three fundamental items that we need to develop to expand SimPEG's capability to handle large scale EM problems are: 

1. Interpolation (between meshes)
2. Deciding what to store or not (e.g. sensitivity, fields) and where
3. Parallelization (choice of package? `dask`)

### Interpolation between meshes

To handle large-scale EM problems (e.g. CSEM, MT, AEM), 
one of the fundamental functionality is having functionality to 
interpolate from one mesh to the other. 
First priority will be UBC-style volumetric nested average function using Octree code

![image](https://user-images.githubusercontent.com/6054371/61306452-a83f7f00-a7ba-11e9-9588-a58c7bb0c6d5.png)

There can be various use cases: 

- MT: have one global mesh but generate a mesh for each frequency
- AEM: have one global mesh (or several depending upon the size), but generate a mesh for each source-receiver pair (or even at each time or frequency) 
- CSEM: similar to AEM (particularly ones having short spacing; e.g. Vulcan system)

### What to store or not and where?

This could be pretty big topic and very problem-dependent. For instance, consider an AEM problem having lots of soundings, but its footprint (or sensitivity) is quite localized (~hundreds of meter for each sounding). In this case I would

- Store: mesh interpolation, predicted data, sensitivity matrix for each source-receiver pair
- Not store: factorization (assuming that we're using direct solver), fields

Because simulation is cheap in this case. 

However, when dealing with a problem like MT, which requires large mesh to solve, I would

- Store: mesh interpolation, predicted data, fields (may be in SSD; use `zarr`?)
- Store (?): factorization (assuming direct solver; but not for iterative solver)
- Not store: sensitivity matrix

### Parallelization

Choices are:

- 'dask'
- 'multiproceesing'
- 'joblib'
- 'mpi4py`

May be good starting point can be simply parallelizing simulation assuming that we 1000 different resistivity models that we would like to compute EM responses.

**Comment by thast** [comment]
Whiteboard of the morning:

![2019-07-17 11 55 16](https://user-images.githubusercontent.com/13682747/61392876-b81b9980-a874-11e9-9982-4b7a9047ab1d.jpg)
![2019-07-17 11 55 10](https://user-images.githubusercontent.com/13682747/61392877-b81b9980-a874-11e9-9be5-551b65de6416.jpg)
![2019-07-17 11 36 43](https://user-images.githubusercontent.com/13682747/61392879-b81b9980-a874-11e9-95dd-b2aac6001cc9.jpg)
![2019-07-17 11 36 29](https://user-images.githubusercontent.com/13682747/61392881-b81b9980-a874-11e9-8b6a-4d0be738f66f.jpg)
![2019-07-17 10 36 02](https://user-images.githubusercontent.com/13682747/61392883-b81b9980-a874-11e9-8d00-6c123b5b0465.jpg)
![2019-07-17 10 35 52](https://user-images.githubusercontent.com/13682747/61392884-b81b9980-a874-11e9-8525-7375b0f982e4.jpg)
![2019-07-17 10 35 47](https://user-images.githubusercontent.com/13682747/61392885-b81b9980-a874-11e9-84bf-335485ab3bb3.jpg)
![2019-07-17 10 35 40](https://user-images.githubusercontent.com/13682747/61392886-b8b43000-a874-11e9-89c0-0be450e3f0b0.jpg)
![2019-07-17 12 18 59](https://user-images.githubusercontent.com/13682747/61392888-b8b43000-a874-11e9-8683-16c862cc5e9b.jpg)
![2019-07-17 12 09 58](https://user-images.githubusercontent.com/13682747/61392889-b8b43000-a874-11e9-8486-4cb572b31a62.jpg)
![2019-07-17 12 08 48](https://user-images.githubusercontent.com/13682747/61392890-b8b43000-a874-11e9-95af-57cc61464508.jpg)
![2019-07-17 12 08 47](https://user-images.githubusercontent.com/13682747/61392891-b8b43000-a874-11e9-9830-f057f9af78d9.jpg)

**Comment by thast** [comment]
Before starting the afternoon:
![2019-07-17 13 48 16](https://user-images.githubusercontent.com/13682747/61399938-0dab7280-a884-11e9-8415-75be8ae653a6.jpg)
![2019-07-17 13 48 08](https://user-images.githubusercontent.com/13682747/61399940-0dab7280-a884-11e9-939b-40c01779668b.jpg)
![2019-07-17 13 48 02](https://user-images.githubusercontent.com/13682747/61399941-0dab7280-a884-11e9-93c0-b7e216c6f2f2.jpg)
![2019-07-17 13 47 56](https://user-images.githubusercontent.com/13682747/61399942-0dab7280-a884-11e9-9038-9a7d43c6dc81.jpg)
![2019-07-17 13 47 45](https://user-images.githubusercontent.com/13682747/61399943-0dab7280-a884-11e9-9612-f552e9642009.jpg)
![2019-07-17 13 48 19](https://user-images.githubusercontent.com/13682747/61399944-0e440900-a884-11e9-9360-6f0893814440.jpg)

**Comment by thast** [comment]
Tiles and paralleization PF:
![2019-07-17 14 32 56](https://user-images.githubusercontent.com/13682747/61401680-d1c5dc80-a886-11e9-9015-305fd6475d5d.jpg)

**Comment by thast** [comment]
`simpeg 1.0` and ToDos:
![2019-07-17 16 24 14](https://user-images.githubusercontent.com/13682747/61409100-5bc97180-a896-11e9-9c7c-7d761304b77c.jpg)
![2019-07-17 16 06 08](https://user-images.githubusercontent.com/13682747/61409101-5bc97180-a896-11e9-93df-819ed3d4ac50.jpg)

**Comment by rowanc1** [comment]
Thanks for keeping notes!
