### ISSUE TITLE
Laguna El Maule Example results with opposites sign

### ISSUE THREAD

**Issue by jabascut** [simpeg/simpeg#920]
I ran the Laguna El Maule example with Simpeg 0.14.2 and compared the inverted density model with Miller et al. 2016 (Paper presenting the gravity survey of Laguna El Maule). Both results are very similar, but the inverted densities of SimPEG have the opposite sign of the Miller et al. densities. The Miller et al. results, which show a negative density anomaly, have more sense because they are associated with a magmatic camera. Please could confirm if there is an error in the example? 

Regards

Juan A. Bascur

**Comment by lheagy** [comment]
cc @domfournier , @craigmillernz: would you mind looking into this?

**Comment by rolandhill** [comment]
Hi,
There appears to be an issue in the gravity inversion code rather than the example. I ran my own models and found density lows underneath gravity highs. It looks right, just inverted. If you check the SimPEG gravity example on the web site you will find it does the same thing. The gravity high is on the left and the gravity low on the right, however the low density model is on the left and the high one on the right (ie inverted).

https://docs.simpeg.xyz/content/tutorials/03-gravity/plot_inv_1b_gravity_anomaly_irls.html#defining-a-tensor-mesh

Regards,
Roland Hill

**Comment by rolandhill** [comment]
... or is this because of a positive up convention?

**Comment by jcapriot** [comment]
SimPEG does have a consistent right handed coordinate system convention where z is positive up.

**Comment by craigmillernz** [comment]
This is a bug which we have fixed and should be in the next release.  SimPEG expects a "postive up" convention, which is a bit unintuitive for gravity but makes sense for other SimPEG internals.  If you import your data using the `readUBCgravityObservations`  function that reads in a UBC format obs or grv file (where negative residual gravity anomalies are negative sign) then simpeg will now flip the sign to handle it's internal conventions properly.

**Comment by domfournier** [comment]
Will be addressed in PR #922
